import os
import re

base_dir = r"c:\Users\ADMIN\Desktop\Mystic Digital Solutions\secteurs"

texts = {
    "juridique.html": "Les cabinets d'avocats, notaires et directions juridiques perdent souvent un temps précieux dans des tâches chronophages : recherche de jurisprudence, rédaction manuelle d'actes hautement répétitifs et fastidieux suivi des nombreux dossiers d'archives purement physiques. Afin de rester compétitives, ces professions réglementées doivent se moderniser. MDS digitalise l'intégralité de vos processus lourds et anciens avec les plus hauts standards de sécurité, de stricte confidentialité et d'absolue conformité légale. Notre approche totalement sur mesure garantit une transition fluide, douce et sécurisée vers le tout-numérique professionnel. Libérez-vous durablement de toutes vos tâches administratives pour enfin toujours pouvoir vous concentrer uniquement sur votre indispensable conseil expert et à très forte valeur ajoutée vitale pour vos propres clients exigeants.",
    "sante.html": "Les établissements de santé modernes, des grandes cliniques aux importants centres hospitaliers régionaux, doivent relever l'immense défi de la délicate gestion des importantes données informatisées ou manuelles de nombreux patients. MDS vous accompagne efficacement et sereinement dans l'indispensable numérisation et digitalisation complètes, absolues et hautement sécurisées de vos fondamentaux workflows médicaux et strictement administratifs. Du parfait déploiement de dossiers patients numérisés extrêmement sécurisés (DPN de pointe) aux excellentes solutions novatrices de pratique de télémédecine pleinement intégrées et très fiables, nous mettons chaque jour avec fierté et assurance l'excellence de notre précieuse technologie au service de l'ensemble des remarquables professionnels de nos chers systèmes de santé locaux.",
    "education.html": "Les écoles innovantes, les universités réputées et l'ensemble des sérieux centres actifs et impliqués de formation continue doivent en permanence réinventer avec brio la nature de leurs parcours pédagogiques actuels pour intelligemment répondre, toujours avec rigueur, aux toutes nouvelles et fortes exigences imposées sans cesse par l'omniprésent monde de plus en plus profondément, grandement et durablement numérique. MDS fournit en réponse des plateformes fluides d'e-learning véritablement engageantes et totalement sur mesure pour les apprenants. Nous accompagnons pas à pas chaque acteur majeur avec efficience dans l'amélioration continue des moyens d'acquisition, l'évolution profonde de tout le cher secteur éducatif pour de plus grands horizons ouverts.",
    "btp.html": "Le secteur si rigoureux et technique de la grande construction civile moderne comme de l'ensemble des chantiers de travaux publics majeurs implique inéluctablement, et à tout instant, la gestion complexe d'énormes quantités de matériaux de construction de première ou seconde ligne, et le constant suivi avec rigueur, perspicacité et ponctualité de l'avancée concrète des travaux. MDS révolutionne le BTP classique et souvent perçu lourd avec la précision fine de systèmes efficients de suivi et guidage des projets concrets. Nous œuvrons pour significativement améliorer avec aisance votre indéniable belle rentabilité finale, optimiser largement chaque ressource employée sur vos sites constructibles ainsi qu'aider à la réussite de toutes vos grandes infrastructures en devenir sur l'immense terrain.",
    "startups.html": "L'écosystème hautement concurrentiel et très dynamique de la tech moderne accueille tous les jours de formidables jeunes et très ambitieuses entreprises innovantes avec d'innombrables attentes incroyablement exigeantes concernant toutes les technologies avancées nécessaires : besoin pressant de grande scalabilité adaptative, de très saine et forte flexibilité ou agilité constante et rapide, d'architectures et infrastructures hautement résilientes capables d'incessablement et durablement accompagner la vertigineuse transformation fulgurante des idées pures. MDS est véritablement et fondamentalement ce fort partenaire d'exception attendu : notre immense expertise très experte dans l'art de concevoir chaque projet comme des plateformes technologiques premium apporte la vélocité requise absolue pour totalement réussir sa croissance rapide et sereine.",
    "ong.html": "Les multiples organisations non gouvernementales majeures ainsi que les discrètes et actives précieuses associations solidaires travaillent souvent sans relâche aux côtés des plus vulnérables tous les jours très directement sur un terrain réputé complexe avec très malheureusement des précieuses mais souvent trop minces ressources matérielles courantes ou purement financières. Les solutions technologiques très accessibles et robustes que MDS fournit activement permettent fondamentalement à chaque association d'assurer un suivi, des collectes d'informations précises de terrain ainsi qu'un exceptionnel reporting rigoureux, clair, moderne et intelligent pour sans relâche conforter, rassurer et encourager tous ses fidèles et solides et essentiels si chers bailleurs et précieux donateurs sans l'aide et concours desquels rien ne s'accomplit parfaitement ou bien.",
    "agritech.html": "Au cœur du continent, la grande agriculture performante de demain a vitalement, grandement et activement enfin commencé une forte et très bienvenue importante mutation profonde grandement favorisée et propulsée en grande échelle par les spectaculaires essors du révolutionnaire secteur digital très moderne indispensable aujourd'hui aux cultivateurs, producteurs ou regroupements coopératifs du monde rural moderne et de ses nombreux agro-industriels très investis. En associant judicieusement les plus fortes analyses fines de la très précieuse donnée concrète captée directement du terrain fertile, de l'irrigation aux moissons, l'expertise pointue et logicielle complète proposée et mise habilement en place techniquement par le cabinet MDS vient véritablement aider et supporter sereinement toute la chaîne vitale des immenses récoltes vivrières ou d'exportations modernes.",
    "fintech.html": "Le très passionnant grand et rigide univers très réglementé résolument international de la finance classique tout comme celui bancaire institutionnel ont très indubitablement, totalement, profondément et irrémédiablement vu naître et évoluer des prodigieuses merveilles telles les incontournables innovations et toutes récentes créatives révolutions purement, incontestablement purement numériques : le prolifique fabuleux secteur foisonnant si puissant des tout nouveaux systèmes intelligents de multiples et diversifiés paiements tous sans exception mobiles. MDS vous apporte avec certitude de la haute valeur technologique de conformité avec les portefeuilles ou logiciels pour vous garantir pleinement d'opérer confortablement dans toute cette immense arène technofinancière à tous vos formidables et multiples partenaires et si nombreux clients en ligne connectés avec l'application web ou mobile conçue par nous.",
    "logistique.html": "Le monde trépidant de la complexe et constante logistique du continent, tout comme l'univers très lié à lui du colossal transport physique des denses biens, implique obligatoirement par toute définition basique ou de haute performance, le plus fort niveau nécessaire hautement crucial de toute la visibilité d'ensemble continue sans faille et une extrême minutieuse coordination sans aucun équivoque à chaque étape précise charnière du grand réseau d'acheminement, d'entreposage temporaire et d'ultime livraisons. MDS accompagne la modernité impressionnante de tous les impressionnants et multiples défis ardus inhérents aux flottes de routiers avec la géolocalisation ou au maritime afin que l'ensemble entier fluide du maillon ne comporte absolument jamais de failles.",
    "tourisme.html": "À l'ère d'un engouement formidable de l'hôtellerie mondiale, ce beau secteur prestigieux du lointain inoubliable voyage a plus que jamais un irrépréhensible fort besoin d'excellentissimes, douces et attractives somptueuses superbes et conviviales nombreuses riches luxueuses attractives lumineuses formidables séjours d'expériences particulièrement uniques adaptées singulièrement à ses hôtes raffinés ou routards enthousiastes. Que ce grand hôtel magnifique, belle belle modeste ou fière chaleureuse grande et digne auberge rurale soit totalement aidée pour capter sa nouvelle superbe exigeante clientèle : voici toute la passionnante de MDS. Nous mettons joyeusement une fierté totale exceptionnelle à déployer sans pareils d'exceptionnels de grands complets de gestion intégrés parfaitement digitaux (exemples: PMS, réservations hôtelières directes etc.)."
}

for file, new_text in texts.items():
    filepath = os.path.join(base_dir, file)
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # regex to find the section and specific P
    pattern = re.compile(r'(<section\s+class="sector-context"[^>]*>.*?<div\s+class="container"[^>]*>.*?<p\s+class=")([^"]*)(".*?>)(.*?)(</p>)', re.DOTALL)
    
    def replacer(match):
        classes = match.group(2)
        if 'sector-context-desc' not in classes:
            classes = classes + ' sector-context-desc'
        
        return match.group(1) + classes + match.group(3) + new_text + match.group(5)
    
    new_content = pattern.sub(replacer, content)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"Updated {file}")
